//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_LuuDucQuang_10121201.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHDN
    {
        public string ID { get; set; }
        public string MaHDN { get; set; }
        public string MaMP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> Dongia { get; set; }
        public Nullable<int> Tongtien { get; set; }
    
        public virtual Hoadonnhap Hoadonnhap { get; set; }
        public virtual ThongTinMyPham ThongTinMyPham { get; set; }
    }
}
