//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_LuuDucQuang_10121201.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadonnhap()
        {
            this.ChitietHDNs = new HashSet<ChitietHDN>();
        }
    
        public string MaHDN { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHDN> ChitietHDNs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
