//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_LuuDucQuang_10121201.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiMyPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiMyPham()
        {
            this.ThongTinMyPhams = new HashSet<ThongTinMyPham>();
        }
    
        public string MaloaiMP { get; set; }
        public string TenloaiMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinMyPham> ThongTinMyPhams { get; set; }
    }
}
