//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_LuuDucQuang_10121201.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLMyPhamCuaCuaHangBanMyPhamEntities : DbContext
    {
        public QLMyPhamCuaCuaHangBanMyPhamEntities()
            : base("name=QLMyPhamCuaCuaHangBanMyPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChitietHDB> ChitietHDBs { get; set; }
        public virtual DbSet<ChitietHDN> ChitietHDNs { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<Hoadonban> Hoadonbans { get; set; }
        public virtual DbSet<Hoadonnhap> Hoadonnhaps { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiMyPham> LoaiMyPhams { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinMyPham> ThongTinMyPhams { get; set; }
        public virtual DbSet<Tonkho> Tonkhoes { get; set; }
    
        public virtual ObjectResult<SP_SPbancham_Result> SP_SPbancham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SPbancham_Result>("SP_SPbancham");
        }
    
        public virtual ObjectResult<SP_SPbanchay_Result> SP_SPbanchay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SPbanchay_Result>("SP_SPbanchay");
        }
    
        public virtual ObjectResult<SP_SPsaphet_Result> SP_SPsaphet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SPsaphet_Result>("SP_SPsaphet");
        }
    
        public virtual ObjectResult<SP_thongkenamHDB_Result> SP_thongkenamHDB(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_thongkenamHDB_Result>("SP_thongkenamHDB", namParameter);
        }
    
        public virtual ObjectResult<SP_thongkenamHDN_Result> SP_thongkenamHDN(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_thongkenamHDN_Result>("SP_thongkenamHDN", namParameter);
        }
    
        public virtual ObjectResult<SP_thongkethangHDB_Result> SP_thongkethangHDB(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_thongkethangHDB_Result>("SP_thongkethangHDB", thangParameter);
        }
    
        public virtual ObjectResult<SP_thongkethangHDN_Result> SP_thongkethangHDN(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_thongkethangHDN_Result>("SP_thongkethangHDN", thangParameter);
        }
    
        public virtual ObjectResult<SP_Timthoigian_Result> SP_Timthoigian(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Timthoigian_Result>("SP_Timthoigian", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SP_TimthoigianHDN_Result> SP_TimthoigianHDN(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TimthoigianHDN_Result>("SP_TimthoigianHDN", startDateParameter, endDateParameter);
        }
    }
}
