//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_LuuDucQuang_10121201.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinMyPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinMyPham()
        {
            this.ChitietHDBs = new HashSet<ChitietHDB>();
            this.ChitietHDNs = new HashSet<ChitietHDN>();
        }
    
        public string MaMP { get; set; }
        public string TenMP { get; set; }
        public string Dungtich { get; set; }
        public string MaloaiMP { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> Giaban { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHDB> ChitietHDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHDN> ChitietHDNs { get; set; }
        public virtual LoaiMyPham LoaiMyPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Tonkho Tonkho { get; set; }
    }
}
